name: lighter-dev
channels:
- https://www.idiap.ch/software/bob/conda
- anjos
- defaults
dependencies:
- python=3.7
- click >=7
- click-plugins
- termcolor
- requests
- pyyaml >=5.1
- nose
- sphinx
- coverage
- ipdb
- bob.buildout
