{% set version = "52" %}

package:
  name: deconz
  version: {{ version }}

source:
  git_url: https://github.com/Kane610/deconz
  git_rev: {{ version }}

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - aiohttp

test:
  imports:
    - deconz

about:
  home: https://github.com/Kane610/deconz
  license: MIT
  summary: 'Python library wrapping deconz rest api for home-assistant'

extra:
  recipe-maintainers:
    - anjos
