{% set name = 'lighter' %}
{% set version = load_setup_py_data()['version'] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - lighter = lighter.scripts.lighter:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - click >=7
    - click-plugins
    - termcolor
    - requests
    - pyyaml >=5.1
    - python-dateutil
    - websocket-client

test:
  imports:
    - {{ name }}

  requires:
    - nose
    - coverage

  commands:
    - lighter --help
    - nosetests -sv --with-coverage --cover-package={{ name }} {{ name }}

about:
  home: https://github.com/anjos/lighter
  license: GPLv3
  summary: Utilities for managing the ZigBee home stuff
  license_family: GPL
